# Copyright (c) 2026 Lukasz Stalmirski
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import sys
import io
import yaml
import vulkan

class ResolvedEnum:
    def __init__( self, enum: vulkan.Enum, display_name: str ):
        self.name = display_name
        self.enum = enum

def write_header( out: io.TextIOBase ):
    out.write( '// This file is generated by gen_names.py, do not edit manually\n\n' )
    out.write( '#pragma once\n' )
    out.write( '#include <string>\n' )
    out.write( "#include <string_view>\n" )
    out.write( '#include <charconv>\n' )
    out.write( '#include <fmt/format.h>\n\n' )

    out.write( '#include "Utils/fnv_hash.h"\n' )
    out.write( '#include "Utils/string_builder.h"\n\n' )

    out.write( 'namespace Profiler {\n' )
    out.write( 'class DeviceProfilerStringSerializerGenerated {\n' )
    out.write( 'public:\n' )
    out.write( '  static constexpr const char* DefaultFlagsSeparator = FlagsStringBuilder::DefaultFlagsSeparator;\n\n' )

def write_footer( out: io.TextIOBase ):
    out.write( '};\n' )
    out.write( '} // namespace Profiler\n' )

def write_serialize_function( out: io.TextIOBase, entry: dict ):
    enum_type = entry.get( 'Type' )
    function_name = entry.get( 'Serialize' )
    combine_bits = 'Bits' in entry

    out.write( f'  std::string {function_name}( {enum_type} value' )
    if combine_bits:
        out.write( ', const char* separator = DefaultFlagsSeparator' )
    out.write( ') const {\n' )

    if combine_bits:
        bits = entry.get( 'Bits', [] )
        out.write( '    FlagsStringBuilder builder(separator);\n' )
        for value in bits:
            if value.enum.protect is not None:
                out.write( f'#ifdef {value.enum.protect}\n' )
            out.write( f'    if(value & {value.enum.name})\n' )
            out.write( f'      builder.AddFlag("{value.name}");\n' )
            if value.enum.protect is not None:
                out.write( '#endif\n' )
        out.write( f'    builder.AddUnknownFlags(value, {len(bits)});\n' )
        out.write( '    return builder.BuildString();\n' )

    else:
        values = entry.get( 'Values', [] )
        out.write( '    switch(value) {\n' )
        for value in values:
            if value.enum.protect is not None:
                out.write( f'#ifdef {value.enum.protect}\n' )
            out.write( f'    case {value.enum.name}:\n' )
            out.write( f'      return "{value.name}";\n' )
            if value.enum.protect is not None:
                out.write( '#endif\n' )
        out.write( '    default:\n' )
        out.write( '      return std::to_string(static_cast<uint64_t>(value));\n' )
        out.write( '    }\n' )

    out.write('  }\n\n')

def write_deserialize_function( out: io.TextIOBase, entry: dict ):
    enum_type = entry.get( 'Type' )
    function_name = entry.get( 'Deserialize' )
    combine_bits = 'Bits' in entry

    out.write( f'  {enum_type} {function_name}(const std::string_view& str' )
    if combine_bits:
        out.write( ', const char* separator = DefaultFlagsSeparator' )
    out.write( ') const {\n' )

    if combine_bits:
        bits = entry.get( 'Bits', [] )
        out.write( f'    {enum_type} result = static_cast<{enum_type}>(0);\n' )
        out.write( '    size_t start = 0;\n' )
        out.write( '    size_t separatorLength = strlen(separator);\n' )
        out.write( '    while(start < str.size()) {\n' )
        out.write( '      size_t end = str.find(separator, start);\n' )
        out.write( '      if(end == std::string_view::npos)\n' )
        out.write( '        end = str.size();\n' )
        out.write( '      switch(FNV(str.substr(start, end - start))) {\n' )
        for value in bits:
            if value.enum.protect is not None:
                out.write( f'#ifdef {value.enum.protect}\n' )
            out.write( f'      case FNV("{value.name}"):\n' )
            out.write( f'        result |= {value.enum.name};\n' )
            out.write( '        break;\n' )
            if value.enum.protect is not None:
                out.write( '#endif\n' )
        out.write( '      }\n' )
        out.write( '      start = end + separatorLength;\n' )
        out.write( '    }\n' )
        out.write( '    return result;\n' )

    else:
        values = entry.get( 'Values', [] )
        out.write( '    switch(FNV(str)) {\n' )
        for value in values:
            if value.enum.protect is not None:
                out.write( f'#ifdef {value.enum.protect}\n' )
            out.write( f'    case FNV("{value.name}"):\n' )
            out.write( f'      return {value.enum.name};\n' )
            if value.enum.protect is not None:
                out.write( '#endif\n' )
        out.write( '    }\n' )
        out.write( '    uint64_t value = 0;\n' )
        out.write( '    std::from_chars(str.data(), str.data() + str.size(), value);\n' )
        out.write( f'    return static_cast<{enum_type}>(value);\n' )

    out.write( '  }\n\n' )

def resolve_enum( enum: vulkan.Enum, enum_display_name: str ):
    if enum_display_name is None:
        protect_info = ''
        if enum.protect is not None:
            protect_info = f' (-D{enum.protect})'
        print( f'WARNING: Enum value {enum.name} is missing from the input definitions.{protect_info}' )
        return None

    return ResolvedEnum( enum, enum_display_name )

def resolve_enums( input_defs: dict, registry: vulkan.Registry ):
    for entry in input_defs:
        enum_type = entry.get( 'Type' )
        enum_values = entry.get( 'Values' )
        enum_bits = entry.get( 'Bits' )
        enum_ignore = entry.get( 'Ignore', [] )
        enum_resolved = []

        if enum_type is None:
            print( 'ERROR: Each entry must have a "Type" field.' )
            continue
        if enum_bits is not None and enum_values is not None:
            print( f'ERROR: Entry {enum_type} cannot have both "Bits" and "Values" fields.' )
            continue
        if enum_bits is None and enum_values is None:
            print( f'ERROR: Entry {enum_type} must have either "Bits" or "Values" field.' )
            continue

        if enum_bits is not None:
            for enum in registry.get_enums( enum_type ):
                if enum.value.bit_count() != 1: # Skip aliases of zeroed and combined flags
                    continue
                if enum.name in enum_ignore: # Skip ignored enums
                    continue
                resolved_enum = resolve_enum( enum, enum_bits.get( enum.name ) )
                if resolved_enum is not None:
                    enum_resolved.append( resolved_enum )
            entry['Bits'] = enum_resolved

        if enum_values is not None:
            for enum in registry.get_enums( enum_type ):
                if enum.name in enum_ignore: # Skip ignored enums
                    continue
                resolved_enum = resolve_enum( enum, enum_values.get( enum.name ) )
                if resolved_enum is not None:
                    enum_resolved.append( resolved_enum )
            entry['Values'] = enum_resolved

def write_output( out: io.TextIOBase, input_defs: dict ):
    write_header( out )
    for entry in input_defs:
        if 'Serialize' in entry.keys():
            write_serialize_function( out, entry )
        if 'Deserialize' in entry.keys():
            write_deserialize_function( out, entry )
    write_footer( out )

if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser( description='Generate string serializer for Vulkan enums.' )
    parser.add_argument( 'input', help='Path to the input YAML file.' )
    parser.add_argument( '--output', help='Path to the output file. If not provided, the output will be written to stdout.' )
    parser.add_argument( '--registry', help='Path to the Vulkan registry XML file. Required if --validate is set.' )
    parser.add_argument( '--enableBetaExtensions', action='store_true', help='Enable enums from beta extensions.' )
    args = parser.parse_args()

    with open( args.input, 'r' ) as f:
        input_defs = yaml.safe_load( f )

    registry = vulkan.load_registry( args.registry )
    registry.enable_beta_extensions = args.enableBetaExtensions

    resolve_enums( input_defs, registry )

    if args.output:
        with open( args.output, 'w' ) as out:
            write_output( out, input_defs )
    else:
        write_output( sys.stdout, input_defs )
