import sys
import os
import subprocess

sys.path.append( sys.argv[1] )

# Generated by CMake
from generated import *

if __name__ == '__main__':
    compiled_shaders_header = os.path.relpath( COMPILED_SHADERS_HEADER )
    glslang_validator = os.path.normpath( VULKAN_SPIRV_COMPILER )
    glslang_validator_options = \
        ['-V'] + \
        ['-o'] + [COMPILED_SHADERS_HEADER_NAME + '.generated.h'] + \
        ['--variable-name'] + [COMPILED_SHADERS_HEADER_NAME]
    subprocess.check_call(
        [glslang_validator] + glslang_validator_options + SHADERS,
        stdout=sys.stdout,
        stderr=sys.stderr )
